### PR TITLE
Migrate to emotion

### PR DESCRIPTION
**Pull request by hyochan**
* Update packages

* Fix tests

* Migrate styled-component to emotion

### CODE REVIEW

**Comment by leotm** [comment]
Curious what made you switch?

And if you're planning on the same in https://github.com/dooboolab/dooboo-native-ts

**Comment by leotm** [comment]
We're ditching styled-components too while re-writing our app (RN + TS), but reverting back to default RN Stylesheets for now.

I'm less concerned for [performance](https://github.com/styled-components/styled-components/issues/1523#issuecomment-366011138) but happy with the less verbosity to simplify our huge 3-year-old project with legacy code/classes/debt.

**Comment by hyochan** [comment]
@leotm Hey thanks for the discussion. Actually, I've made this decision for two reasons.
1. Had bad experiencing in `@types/styled-components. This very often breaks. There were many related issues according to this in [styled-components](https://github.com/styled-components/styled-components).
2. My latest UI framework, [material-ui](https://material-ui.com/, also changed to [emotion](https://material-ui.com/guides/interoperability/#emotion). I'm not sure about their decision but it made me think that `emotion` is better library.

**Comment by leotm** [comment]
Fair enough yes especially within View/TouchableOpacity, hard to detect RN CSS syntax within unlinted backticks and miscalculations like divide by zero errors :D

**Comment by leotm** [comment]
I didn't find the styled-components regular CSS syntax beneficial either, after adapting quickly to RN CSS.
The styled props were nice tho.

**Comment by leotm** [comment]
https://github.com/mui-org/material-ui/issues/22342

**Pull request merged**
